---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014

documentation:
  swagger:
    services:
      -
        name: Ms Auth
        url: ${MSAUTH_DOCS}
        version: 2.0
      -
        name: Ms Complaint
        url: ${MSCOMPLAINT_DOCS}
        version: 2.0
      -
        name: Ms Subsriber
        url: ${MSSUBSCRIBER_DOCS}
        version: 2.0
      -
        name: Ms Team
        url: ${MSTEAM_DOCS}
        version: 2.0
