---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014

documentation:
  swagger:
    services:
      - name: ms-auth
        url: ${MSAUTH_DOCS}
        version: 2.0
      - name: ms-complaint
        url: ${MSCOMPLAINT_DOCS}
        version: 2.0
      - name: ms-subscriber
        url: ${MSSUBSCRIBER_DOCS}
        version: 2.0
      - name: ms-team
        url: ${MSTEAM_DOCS}
        version: 2.0
      - name: ms-alarm
        url: ${MSALARM_DOCS}
        version: 2.0
      - name: ms-mail
        url: ${MSMAIL_DOCS}
        version: 2.0
      - name: ms-storage
        url: ${MSSTORAGE_DOCS}
        version: 2.0

